### ISSUE TITLE
Timeshift-spy doesn't work for me since I updated to Linux Mint 20.1

### ISSUE THREAD

**Issue by jvschiavo** [NicoG60/Timeshift-Spy#2]
I gave it another try today and it always says "Backup device not found".

![timeshift-spy](https://user-images.githubusercontent.com/20977075/117435958-ced92780-af04-11eb-8f41-a147498bc9cc.png)

**Comment by amithiel** [comment]
> I gave it another try today and it always says "Backup device not found".
> 
> ![timeshift-spy](https://user-images.githubusercontent.com/20977075/117435958-ced92780-af04-11eb-8f41-a147498bc9cc.png)

Hi!
Came here for the same reason, and i figured by myself.
Go to the applet config file ( for me it's ~/.local/share/cinnamon/applets )
edit the file: applet.js

find the line:  this.config_file_path = '/etc/timeshift.json'
Check if timeshift.json really exists on that directory. for me, i had to change to:
 this.config_file_path = '/etc/timeshift/timeshift.json'
then, just hit alt+f2, type "r" and hit enter to restart cinnamon.
cheers

**Comment by NicoG60** [comment]
Hi thanks for finding that out. I'll implement that in quickly and close this issue when it's done
